### ISSUE TITLE
Plain text should not be clickable for desktop filter categories

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#151] opened 2019-04-12 15:02 UTC
Within the filters, currently the filter category (e.g. "Color") is clickable on the desktop even though it doesn't do anything. We either have to make it not get keyboard focus and not be clickable, OR we need to make it actually work to expand and collapse the sections the way I assume it is supposed to work on mobile. Please do whatever is easier.

**Comment by aevanson** [comment] 2019-04-15 13:41
This is a duplicate of #125. The planned functionality is to make the categories behave like accordions and expand/contract.

**Comment by aevanson** [comment] 2019-04-15 13:43
Duplicate of #125.

**Closed by aevanson** 2019-04-15 13:43 UTC
Labels: Accessibility
