### ISSUE TITLE
Mobile safari layout issue for About page

### ISSUE THREAD

**Issue by alisonrae** [PublicisSapient/accessible-ecommerce-demo#232] opened 2019-05-17 01:08 UTC
![B13F6C9E-1601-45D8-9BDA-5335B19393AC](https://user-images.githubusercontent.com/4038339/57896527-2fa25d80-781f-11e9-9ea0-e73db0d9dc7d.png)
Mobile safari has weird layout issues for About page.

**Comment by aevanson** [comment] 2019-05-17 13:57
Duplicate of #231

**Closed by aevanson** 2019-05-17 13:57 UTC
Labels: bug
